-- Generated by fares.top - https://fares.top
addappid(1296360)
addappid(1296361,0,"cd8bd502bab629ae4c436ea94afeb2370b50ec2cc8919f583bc3989b20b46edc")
setManifestid(1296361,"4448900037900655732")

--[[
This file Generated using fares.top Website 
-----> join discord Server : https://discord.gg/steamgames 
]]