-- This lua file has been fetched from the bot VICTOR which is the exclusive property of Piracy Lords server.
-- Redistribution of VICTORs files is not allowed AT ALL
-- Join the offical here: https://discord.gg/piracylords

addappid(2742830)
addappid(2742831, 1114342112, "c2a5386e1f6feabad976ffd5e88028153d29a7d432483ee3763229bff9075fcb")
--setManifestid(2742831, "2354762707692538649", 1799770769)

-- DLC's found!
addappid(3580220) -- Monster Train 2 Digital Compendium

-- Generated By [Manilua Creator v3.2.2.3] ~ Game: Monster Train 2
-- Discord: toxichome ~ https://discord.gg/2bv9T3NfVP