addappid(3238670)
addappid(3238671, 248590768, "13cd290bb2c0f5a7295e7fb13e3a40c979c54085244db28c2251421edde94157")
--setManifestid(3238671, "5395330052246093536", 496375283)

-- All DLC's already processed!

-- Generated By [Manilua Creator v3.2.2.4] ~ Game: Conquest Dark
-- Discord: toxichome ~ https://discord.gg/2bv9T3NfVP